# Generated by Django 3.1.7 on 2021-03-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('choice1', models.TextField(verbose_name='choice1')),
                ('choice2', models.TextField(verbose_name='choice2')),
                ('choice3', models.TextField(verbose_name='choice3')),
                ('choice4', models.TextField(verbose_name='choice4')),
                ('answer', models.CharField(max_length=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qv1.quiz')),
            ],
        ),
    ]
